### ISSUE TITLE
FrameworkElementExtensions.Ancestor causes an XAML memory leak

### ISSUE THREAD

**Issue by sylveon** [CommunityToolkit/Windows#107]
## Describe the bug
Setting the `AncestorType` property on an object will store the parent of the object as an attached property, causing a reference loop (the parent holds a reference to the child, the child holds a reference to the parent).

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce

- [x] Can this be reproduced in the Sample App? Technically yes, although the memory usage impact is hard to notice because there is a lot else going on in the sample app.

1. Use AncestorType in some XAML content
2. Load the XAML content (eg navigate to it in a frame)
3. Unload the XAML content (eg navigate away from it, remove it from the visual tree)
4. Notice that the XAML elements are never freed correctly, keep taking memory, and weak references will still resolve.

## Expected behavior
The elements should be freed.

## Screenshots
No screenshots needed.

## Environment

```
NuGet Package(s): N/A

Package Version(s): N/A

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [x] May 2020 Update (19041)
- [ ] Insider Build (build number: )

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [x] May 2020 Update (19041)
- [x] Insider Build (22000)

Device form factor:
- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] 2019 Preview (version: )
- [x] 2022 Preview (version 17.0 preview 2.1)
```

## Additional context
Found while doing a C++ port, so bug happens on latest commit. The solution to this issue would be to set the `Ancestor` attached property to `null` in the `Unloaded` event handler.

**Comment by michael-hawker** [comment]
@sylveon with the move to the new repo I setup some better tests for this, but was unable to see this capture occur: https://github.com/CommunityToolkit/Windows/pull/105/commits/05ad5d1db74ae9fb14ca1467267a17d708ba8111

I believe the Unloaded event you suggested, would be this one: https://github.com/CommunityToolkit/Windows/pull/105/commits/022b4bfde61f945ae6e4d1aeae9c61dd7a5190cc#diff-580bc71d9c4f313076c44a4b78b36e7cbb2bc490039efc2f789b48bbded56390R81-R93

Any thoughts? Think it has to be a more complex scenario than this one? I tried just on the page removing children and a whole frame navigation... In both cases I saw the reference being cleaned. Thanks!

**Comment by sylveon** [comment]
@michael-hawker the leak is between TextBlock and ListView in that code (they both hold a strong reference to each other) - a random TextBox won't show it. The leak is obvious when navigating to and away from a page that uses this attached property - memory won't ever drop back to what it was before you opened it, this is more obvious when you're using a control that is intensive on memory of course.

My solution was indeed to just listen to `Unloaded` within `RelativeAncestor::OnAncestorTypeChanged`
