### ISSUE TITLE
CameraPreview causes XAML compiler error

### ISSUE THREAD

**Issue by BreeceW** [CommunityToolkit/Windows#108]
1. Create new project Blank App, Packaged (WinUI 3 in Desktop)
2. Update to latest stable Microsoft.WindowsAppSDK and Microsoft.Windows.SDK.BuildTools (in my case 1.3.230602002 and 10.0.22621.756, respectively)
3. Build Debug x64 Packaged (everything works as expected)
4. Using package source https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json install CommunityToolkit.WinUI.Controls.CameraPreview latest prerelease 8.0.0-beta.1
5. Everything still builds
6. Add XAML to MainPage.xaml (after removing the default button added by the WinUI template)
```xaml
<Window
    x:Class="NewWinUI3App.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:controls="using:CommunityToolkit.WinUI.Controls"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="using:NewWinUI3App"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">
    <controls:CameraPreview />
</Window>
```
7. Build and get error `1>C:\Users\username\.nuget\packages\microsoft.windowsappsdk\1.3.230602002\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(660,9): Xaml Internal Error error WMC9999: Cannot find type CommunityToolkit.WinUI.Helpers.CameraHelper in module CommunityToolkit.WinUI.Helpers.dll.`

**Comment by michael-hawker** [comment]
I was building the WASDK Sample App within the Toolkit, and the control is 'working', so this seems like more of a packaging issue mostly?

I was only able to see a few frames of the `CameraPreview` before it paused, showed a bit more, then froze again (probably need another issue). We may want to try the 1.4 preview and see if that makes a difference too?

**Comment by BreeceW** [comment]
> I was building the WASDK Sample App within the Toolkit, and the control is 'working', so this seems like more of a packaging issue mostly?

Yes, this issue is about the packaging problem.

> I was only able to see a few frames of the `CameraPreview` before it paused, showed a bit more, then froze again (probably need another issue). We may want to try the 1.4 preview and see if that makes a difference too?

I was also unable to get more than a few frames when I copied the code directly to run it in the 1.3 stable.

**Comment by michael-hawker** [comment]
@BreeceW found the underlying platform issue: https://github.com/microsoft/WindowsAppSDK/issues/2774 - Will need to get more info from the platform team, as it doesn't look to have gotten any traction. 😟

**Comment by BreeceW** [comment]
The packaging issue seems fixed now. Camera still freezes after a few frames, but that’s a separate issue.

**Comment by michael-hawker** [comment]
@BreeceW thanks for reporting back! Our initial packages had an issue if your WASDK app was targeting net7.0-windows, so that may have been what you were seeing? The latest package on NuGet has that resolved.
