### ISSUE TITLE
Use NuGet package references to other components where possible

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Windows#117]
## Background

> I may have been out of the loop while away, why do we have these two like this? This was needed for the extensions because we use them in the Test infrastructure (and maybe because of the Sample App). Are we using things from these in those places too? 
> Otherwise, a regular project reference should work? As it should get resolved locally as a project but as a NuGet reference when built for packaging.
> We needed it for extensions, as to build Labs and use the sub-module elsewhere we needed the extensions as it's part of the tooling itself, but then swap within the Windows repo. If we don't use the Helpers/Primitives in the Sample App/Testing stuff, then we don't need the same approach.

_Originally posted by @michael-hawker in https://github.com/CommunityToolkit/Windows/pull/77#discussion_r1253799941_

> This was one of the things we were unsure about, glad to clear that up 👍
> Think I'll open a separate PR and clean them all up.

_Originally posted by @Arlodotexe in https://github.com/CommunityToolkit/Windows/pull/77#discussion_r1258662923_
            
 ## Problem
            
In a Toolkit Component, we should be referencing the NuGet version of other components instead of referencing the csproj directly.

**Comment by michael-hawker** [comment]
To clarify, inside the Windows repo, we can reference the csproj, but we should be able to do that via regular VS path include from the Editor vs. having special properties for each component.

For things like Labs, then yes, they should be NuGet references of the packages.

The exception is if it's something we leverage in the Testing infrastructure or Sample App where we'll want to modify the underlying code and make updates to the sub-module at the same time to test. The extensions was the biggest element here, thus why we did the originally property, so when in the Windows repo it can be a project reference, but in the Labs repo it can be a NuGet package.

See:

```xml
  <Choose>
    <When Condition="'$(ToolkitExtensionSourceProject)' == ''">
      <ItemGroup>
        <PackageReference Include="CommunityToolkit.$(DependencyVariant).Extensions" Version="8.0.0-beta.1"/>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <ProjectReference Include="$(ToolkitExtensionSourceProject)"/>
      </ItemGroup>
    </Otherwise>
  </Choose>
```

https://github.com/CommunityToolkit/Tooling-Windows-Submodule/blob/38728ba616661853b3bbcec9269ab1e362daa72a/ProjectHeads/Tests.Head.props#L21-L32
