### ISSUE TITLE
DispatcherQueueTimerExtensions.Debounce does not work with leading edge action

### ISSUE THREAD

**Issue by huynhsontung** [CommunityToolkit/Windows#143]
### Describe the bug

`Debounce(immediate: true)` does not work with a default timer. When a timer is created, `IsRepeating` is set to true by default. This breaks the logic of Debounce when `immediate: true`. Setting `IsRepeating` to false on the timer fixes this issue.

### Steps to reproduce

1. Create a `DispatcherQueueTimer` using `DispatcherQueue.GetForCurrentThread().CreateTimer()`
2. Use `Debounce()` on that timer with `immediate: true`
3. The action is only triggered once and never again.

### Expected behavior

Subsequent actions should trigger once the timer expires just like without the `immediate` flag.

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [X] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Visual Studio Version

2022

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by michael-hawker** [comment]
Thanks for the issue @huynhsontung, moved this to the new repo. Seems like we just have a couple of simple tests and not one for this scenario: https://github.com/CommunityToolkit/Windows/blob/main/components/Extensions/tests/DispatcherQueueTimerExtensionTests.cs

In immediate mode though, there should be only one firing of the event at the start. It'll only fire again if a request comes in after the elapsed period of time. For my clarity, is that not what you're observing? Or you're saying that it _never fires_ again after the first time?

The docs don't say what the default should be, I filed an issue: https://github.com/MicrosoftDocs/winrt-api/issues/2386

I would have thought `IsRepeating` was false by default, as `DispatcherTimer` didn't have it. I wonder if this was a change in the WASDK version, which platform are you seeing this behavior on? If the two platforms are different defaults, then that seems like a regression we should file against the platform?

In either case, seems like we should add some tests here for this scenario to our matrix to be sure.

**Comment by huynhsontung** [comment]
Hello @michael-hawker, 

In immediate mode, it *never* fires again after the first time.

I am developing for UWP (min version 18362, target version 22000) but I can confirm that `IsRepeating` is true by default for both UWP and WASDK. I can work on a patch for this issue from our end.

**Comment by michael-hawker** [comment]
I'm surprised `IsRepeating` is `true`. I wonder if we missed this fact when we converted these from `DispatcherTimer` helpers to `DispatcherQueueTimer` helpers?

Is there value in these if `IsRepeating` is true? Do we just have to require/document that `IsRepeating` should be turned off for this function to work properly you think?

**Comment by huynhsontung** [comment]
I think the feature should continue to work regardless of `IsRepeating` setting. Users may rely on `IsRepeating` for their own timer logic. Like its non-immediate mode, we can handle the `DispatcherQueueTimer.Tick` event for triggering action as well in this case.

**Comment by michael-hawker** [comment]
Hey @huynhsontung not sure why we didn't resolve or fix this. I had some other Debounce clean-up to do, so I have fixed this in https://github.com/CommunityToolkit/Windows/pull/569 - there was some issues in one of the original tests, so maybe that's why I was confused here in the past.

Feel free to take a look. I'll add a bit more to the new docs page and a test or custom `Tick` call you mention here as well (which I think should work and just get called when the debouncer fires).
