### ISSUE TITLE
TokenizingTextBox version bump

### ISSUE THREAD

**Issue by niels9001** [CommunityToolkit/Windows#161]
See https://github.com/CommunityToolkit/WindowsCommunityToolkit/discussions/4895#discussioncomment-6162638

Version number in the .csproj is 0.0.1, should be bumped up to 8.0.0-beta1.

This is blocking @DmitriMilokhov from using it as he's a dependency on the 7.x of the Control package as well

**Comment by michael-hawker** [comment]
Planning to update all the package version numbers to attempt to rebuild and fix other issues (hopefully). But don't think that's the root issue of their problem, it's probably the mix-match of package versions.

**Comment by michael-hawker** [comment]
Done as part of #162
