### ISSUE TITLE
8.0 RC will install unrelated Uno.* to Windows App Sdk project

### ISSUE THREAD

**Issue by zhuxb711** [CommunityToolkit/Windows#186]
Install any package. TargetFramework was set to net7.0-windows10.0.22621.0, Uno.* will also be installed. Is that the correct behavior?

![image](https://github.com/CommunityToolkit/Windows/assets/42038175/ba70bada-44b1-44ef-9308-d4c48b2fa9e0)

**Comment by zhuxb711** [comment]
@michael-hawker Please correct me if have any miss understanding

**Comment by kmgallahan** [comment]
Probably related / causing 

https://github.com/CommunityToolkit/Windows/discussions/184#discussioncomment-6811870

**Comment by michael-hawker** [comment]
Yes, for Windows App SDK you need to target net6.0-windows... we're investigating various fixes for this. Thanks for filing an issue.

**Comment by michael-hawker** [comment]
`8.0.230828-rc` packages have been pushed to NuGet which should resolve this issue. Thanks for reporting!

**Comment by michael-hawker** [comment]
@vash72 if you target `net7.0-windows10.0.19041` does this still happen?

FYI @Arlodotexe

**Comment by vash72** [comment]
@michael-hawker  upgrading the tfm to `net7.0-windows10.0.19041` solve Uno.* problem (now the project crash at runtime for some resouce loading)

**Comment by Jay-o-Way** [comment]
Does this issue need to be pinned when it's closed?

**Comment by Arlodotexe** [comment]
This issue was fixed before the stable 8.0 release. Full breakdown on why this issue happened can be found here: https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/125#issue-1867533661
