### ISSUE TITLE
Gallery missing in-app sample source code

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Windows#230]
There's a known issue with the sample app not displaying XAML/C# code correctly for some reason, we think it's a build authoring issue, but not sure, we're still investigating. Please bear with us!

_Originally posted by @michael-hawker in https://github.com/CommunityToolkit/Windows/discussions/228#discussioncomment-6941296_

**Comment by Arlodotexe** [comment]
It seems like there's sometimes XAML but never C#

#### C#
![image](https://github.com/CommunityToolkit/Windows/assets/9384894/f1a6155a-f492-4449-98aa-fc9bcb680251)

#### XAML
![image](https://github.com/CommunityToolkit/Windows/assets/9384894/3752be5e-24f0-4077-bf3d-29de82e51c8c)

#### C#
![image](https://github.com/CommunityToolkit/Windows/assets/9384894/98cab196-5c56-42fb-bd4f-ccb62f4642d6)

#### XAML
![image](https://github.com/CommunityToolkit/Windows/assets/9384894/5ef9c0c0-ae4f-4786-b50b-293a1f077d1e)

**Comment by Arlodotexe** [comment]
I tested 3 variants of the app locally.
- Debug
- Release without .NET Native
- Release with .NET Native.

They're all working. @michael-hawker I'm not sure what happened, but it might actually be machine specific. Maybe a git clean was needed or something.

**Comment by ghost1372** [comment]
@Arlodotexe today i compiled WinUI 3 Gallery source code, and i saw this issue there. I think they are related

**Comment by michael-hawker** [comment]
> @Arlodotexe today i compiled WinUI 3 Gallery source code, and i saw this issue there. I think they are related

Thanks for this information, that'd be pretty odd as our gallery app in the store is a UWP app, so think that may just be a coincedence?

---

I reinstalled our initial release build from Thursday 8/31 and it worked as expected (outside of the other issues we discovered and started fixing).

Diff of those changes is here: https://github.com/CommunityToolkit/Windows/compare/9c4749f49ca47cafb9a72c3af2984b78751dcd38...main

There shouldn't be too much functional in here though, but just starting to take a look.

**Comment by michael-hawker** [comment]
Yeah, looking through the changes in the commits and the tooling, its mostly just doc/content changes, very minor. Nothing that should effect sample loading from my understanding. Guess next step is for me to retry building the app and see what happens... Wonder if I should backport the fixes I made while importing the docs repo first... 🤔

**Comment by michael-hawker** [comment]
This is now fixed in the Store, if you go to settings you should see version 8.0.2 of the Sample App.

I need to cherry-pick the commit from another branch to check-in. Had to do with code we had to strip some headers from the samples being displayed. Since it dealt with newlines it seemed like it had different behavior across files based on formatting from the repo/git/machine, etc...
