### ISSUE TITLE
SurfaceLoader.LoadImageAsync always fails in WinUI 3

### ISSUE THREAD

**Issue by Marv51** [CommunityToolkit/Windows#233]
### Describe the bug

I am trying to port my Toolkit 7 usage over to version 8. I am using a PipelineBuilder to create a tiled brush.

This fails currently (was working before) with a **NullReferenceException**.

I have traced back the origin of that exception to [this line in the SurfaceLoader](https://github.com/CommunityToolkit/Windows/blob/34a83a4c4e4caf4fa272f38350b2ce57984c4148/components/Media/src/Helpers/SurfaceLoader.cs#L47)

`var compositor = Window.Current.Compositor;`

There must be another way to get the Compositor in WinUI 3, because Window.Current is always null in WinUI 3.

Not sure if this is still the preferred approach, but in the old repo, the WinUI branch looks like this: 

`var compositor = CompositionTarget.GetCompositorForCurrentThread();`

https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/a10204e648c372f6a6837c5aa40065761847132e/CommunityToolkit.WinUI.UI.Media/Helpers/SurfaceLoader.cs#L45C13-L45C80

### Steps to reproduce

This is a pretty obviously an oversight when porting the UWP code, but here is my code just in case: 

```csharp
Uri _transparentBackground = new Uri("ms-appx:///Images/TransparentBackground.png");

var builder = PipelineBuilder.FromTiles(_transparentBackground, DpiMode.DisplayDpiWith96AsLowerBound);
var brush = builder
            .Shade(Colors.Red, 0.5f)
            .AsBrush();
```

### Expected behavior

No exception expected.

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [X] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [X] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [X] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Additional context

I found a lot of `Window.Current.Compositor` instances in this part of the code. 

Is a `#if WINUI3` the preferred approach?

### Help us help you

I'd prefer someone else to look at this, so that it can be addressed in a timely manner, because I am not at all familiar with the new tooling.

**Comment by michael-hawker** [comment]
Thanks for the report @Marv51, yeah, this got missed in the port. Not sure how as we were comparing against the winui branch. FYI @Arlodotexe.

**Comment by Arlodotexe** [comment]
Possibly related to #235
