### ISSUE TITLE
SettingsCard isn't accessible with Voice Access

### ISSUE THREAD

**Issue by krschau** [CommunityToolkit/Windows#283]
### Describe the bug

When using Voice Access, if you say "show numbers", a clickable SettingsCard doesn't get a number.

In this screenshot, you can see the interactive parts of the cards in the top half get numbers, but the bottom cards, where the entire thing is a button, do not get numbers.
![image](https://github.com/CommunityToolkit/Windows/assets/47155823/45a87d52-c55d-4668-9588-ed3ece6c0070)

In Dev Home, we're using a Command as the action on the SettingsCard. I see that in the Sample Gallery there is no action, but the behavior is the same even when there is.

### Steps to reproduce

```text
1. Enable Voice Access (https://support.microsoft.com/en-us/topic/set-up-voice-access-9fc44e29-12bf-4d86-bc4e-e9bb69df9a0e)
2. Open the Settings Card page in the Sample Gallery
3. Say "show numbers"
4. See screen like above
```

### Expected behavior

Clickable SettingsCards should be able to be interacted with using Voice access.

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [X] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Help us help you

No, I'm unable to contribute a solution.

**Comment by niels9001** [comment]
Fixed in https://github.com/CommunityToolkit/Windows/pull/284
