### ISSUE TITLE
Set up test reporting

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Windows#3]
### Background
Testspaces don't seem to set up in this repo, so they weren't enabled as part of #1.

### Problem
Tests are not reported, and must be observed from the logs directly.

### Solution
Set up test reporting. This can either be testspaces, or the github-provided [Test Reporter](https://github.com/marketplace/actions/test-reporter).

**Comment by michael-hawker** [comment]
#40 is all ready to go, just needs review/approval and merging. Already added the requirement to the branch protection, so no other PR will work until #40 is merged as tests are a requirement now. 🙂

All the tests still passed, so shouldn't be any problems. Thanks!
