### ISSUE TITLE
ExpressionFunctions.ColorLerpRgb does not work

### ISSUE THREAD

**Issue by h82258652** [CommunityToolkit/Windows#303]
### Describe the bug

The `ExpressionFunctions.ColorLerpRgb` does not work.

![image](https://github.com/CommunityToolkit/Windows/assets/5144550/265fab40-cbea-4fa9-b68d-70fa47bec542)
![image](https://github.com/CommunityToolkit/Windows/assets/5144550/27c56f82-5840-4845-9243-6210ef5a77ab)

### Steps to reproduce

```text
Start a color animation with `ExpressionFunctions.ColorLerpRgb`.
```

### Expected behavior

The animation should work as expected.

### Code Platform

- [ ] UWP
- [ ] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by Arlodotexe** [comment]
Closed by https://github.com/CommunityToolkit/Windows/pull/304
