### ISSUE TITLE
ListViewExtensions.AlternateColor only gets applied on hover

### ISSUE THREAD

**Issue by insomniachi** [CommunityToolkit/Windows#327]
### Describe the bug

ListViewExtensions.AlternateColor only gets applied on hover over the item on WinUI3 1.0

### Reproducible in sample app?

- [X] This bug can be reproduced in the sample app.

### Steps to reproduce

```text
Repro on sample app ListViewExtensions page
```

### Expected behavior

Alternate color should get applied when listview loads
![image](https://user-images.githubusercontent.com/6525704/147401071-f64a8a17-108d-4fd7-9547-4c78dafb1c98.png)

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [X] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Visual Studio Version

2022

### Visual Studio Build Number

17.0.4

### Device form factor

Desktop

### Nuget packages

CommunityToolkit 7.1.2

### Help us help you

Yes, but only if others can assist.

**Comment by jsidewhite** [comment]
+1 would love a fix for this for our [DevHome](https://github.com/microsoft/devhome) ListView

**Comment by niels9001** [comment]
@TyJOrtiz Do you think your fix in https://github.com/CommunityToolkit/WindowsCommunityToolkit/pull/4865 is still applicable here?

**Comment by TyJOrtiz** [comment]
> [@TyJOrtiz](https://github.com/TyJOrtiz) Do you think your fix in [CommunityToolkit/WindowsCommunityToolkit#4865](https://github.com/CommunityToolkit/WindowsCommunityToolkit/pull/4865) is still applicable here?


Sometimes the "fix" has issues where the alternate color won't load. but it's rare
