### ISSUE TITLE
Changing the Font family of the Settings Expander doesn't change the text for both Header and Description

### ISSUE THREAD

**Issue by Onotseike** [CommunityToolkit/Windows#332]
### Describe the bug

If you create settings expander and change the font family, the header and Description text is not changed.
It works fin for settings card. See an illustration of the issue below
<img width="1219" alt="image" src="https://github.com/CommunityToolkit/Windows/assets/5883457/f24e647c-4068-4ca3-8ce0-76d08582fb0e">

<img width="1219" alt="image" src="https://github.com/CommunityToolkit/Windows/assets/5883457/0ad824f9-9b2e-4aa0-87cf-3c7e1c1bf133">

### Steps to reproduce

```text
1. Create WinUI project with the toolkit
2. Add a custom font to your project.
3. Add a settings card and change the font family
4. Add s settings expander and change the font family
5. Run app
6. The font family is changed in the settings card but not the settings expander's description and Header texts
```

### Expected behavior

The Header and Description Texts should use the specified font 
`<settings:SettingsExpander x:Uid="Connect_To_Cloud_Cards"
    FontFamily="{StaticResource Monofur-Italic}"
    ItemTemplate="{StaticResource CloudProviderSettingsCards}"
    ItemsSource="{x:Bind ViewModel.CloudProviders}"
    Style="{StaticResource MoonLightSettingsExpanderStyle}" />`

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [X] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [X] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Visual Studio Version

2022

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by niels9001** [comment]
@Onotseike Great catch, PR with fix here: https://github.com/CommunityToolkit/Windows/pull/333
