### ISSUE TITLE
[`RangeSelector`] on WASM draws squares around track controls

### ISSUE THREAD

**Issue by xperiandri** [CommunityToolkit/Windows#386]
### Describe the bug

![image](https://github.com/CommunityToolkit/Windows/assets/2365592/f88ef865-e270-414a-91c7-31656a11b5fb)

### Steps to reproduce

```text
Create a blank Uno app
Add a `RangeSelector` to the main page
Launch WASM head
```

### Expected behavior

No square borders around track controls

### Code Platform

- [ ] UWP
- [ ] WinAppSDK / WinUI 3
- [X] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [X] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [X] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Visual Studio Version

2022

### Help us help you

Yes, but only if others can assist.

**Comment by Arlodotexe** [comment]
Looks like Uno had fixed this in [this PR](https://github.com/unoplatform/uno/pull/13682). This can be reproduced over in https://toolkitlabs.dev, which is using the latest version of Uno from our `main` branch. This appears to be a regression in Uno.

**Comment by michael-hawker** [comment]
This is an Uno issue, their bug is here: https://github.com/unoplatform/uno/issues/10263, it was supposed to have been fixed, hmm.

**Comment by xperiandri** [comment]
So why do they appear if it is fixed?
Or is not it fixed?

**Comment by michael-hawker** [comment]
> So why do they appear if it is fixed? Or is not it fixed?

It was supposedly fixed, but that appears to not be the case. I thought I had seen this work in the interim at one point, so maybe it regressed again. I poked the Uno issue, so that's going to be the best place to follow-up.

**Comment by MartinZikmund** [comment]
The linked issue is not related, we are tracking this in https://github.com/unoplatform/uno/issues/15448, will prioritize it to get the fix out asap
