### ISSUE TITLE
Several packages are incorrectly named on Nuget

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Windows#43]
The `Sizers` are in the `CommunityToolkit.WinUI.Controls` namespace, but the package doesn't really reflect that.

The package name should have the `Controls` part in it as well, but currently it is omitted.

Not sure where that's getting dropped as it's in the project filename: [`CommunityToolkit.WinUI.Controls.Sizers.csproj`](https://github.com/CommunityToolkit/Windows/blob/main/components/Sizers/src/CommunityToolkit.WinUI.Controls.Sizers.csproj).

But the package is instead `CommunityToolkit.WinUI.Sizers`.

**Comment by Arlodotexe** [comment]
@michael-hawker We'll get that fixed. That means we'll need to mark the published `CommunityToolkit.WinUI.Sizers` package as deprecated as well, how do we go about that?

**Comment by Arlodotexe** [comment]
Same problem with Triggers. Something has clearly been misconfigured, and other packages may be affected. Needs investigation.

![image](https://github.com/CommunityToolkit/Windows/assets/9384894/8de64095-e6ce-45ba-ba3c-5be8fcf5acbc)

**Comment by michael-hawker** [comment]
Triggers I'm not sure if it needs it as they're not controls? Definitely Primitives.

To deprecate the package can be done in the Azure Artifacts. Not sure who has permissions to do that besides me, Sergio might.

**Comment by Arlodotexe** [comment]
@niels9001 The PackageId defaults to the name of the component. We should be setting the `PackageId` for these manually.

![image](https://github.com/CommunityToolkit/Windows/assets/9384894/dcb01520-53b2-4c43-8496-197f8fc6971c)

**Comment by Arlodotexe** [comment]
The packages renamed in these PRs need to be deprecated:
- https://github.com/CommunityToolkit/Windows/pull/63
- https://github.com/CommunityToolkit/Windows/pull/64

**Comment by michael-hawker** [comment]
Unlisted the packages with the old identities.
