### ISSUE TITLE
ColorPicker ColorPalette display order

### ISSUE THREAD

**Issue by Marv51** [CommunityToolkit/Windows#447]
### Describe the bug

There is a small but potentially important difference in the colorpicker in 7.x and the new 8.1 colorpicker:
The color palette is shown in a different order. For example, in the default palette, yellow used to be at the bottom left, now it is in the top left. 

Here is a screenshot that illustrates the problem:
![ToolkitBug](https://github.com/CommunityToolkit/Windows/assets/471338/c121c88b-53c7-4716-a565-b559f94fd1fc)

(Please ignore the "Not supported" tooltip.)

### Steps to reproduce

I use the ColorPickerButton, but likely any ColorPicker will have the same issue.

Starting from an empty WinUI3 template, I added a ColorPickerButton and the CommunityToolkit.WinUI.Controls.ColorPicker nuget package.

MainWindow.xaml
```xaml
xmlns:controls="using:CommunityToolkit.WinUI.Controls"
[...]
<controls:ColorPickerButton></controls:ColorPickerButton>
```

App6.csproj
```xml
<TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
[...]
<ItemGroup>
  <PackageReference Include="CommunityToolkit.WinUI.Controls.ColorPicker" Version="8.1.240606-rc" />
  <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1" />
  <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.5.240607001" />
  <Manifest Include="$(ApplicationManifest)" />
</ItemGroup>
```

### Expected behavior

The previous order is described in detail here: 
https://github.com/CommunityToolkit/Windows/blob/0bab2c0359ab33b7ef9868496a2fe5175c5afe6b/components/ColorPicker/src/FluentColorPalette.cs#L12-L44

### Screenshots

See above

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [X] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [X] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [X] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Visual Studio Version

2022

### Visual Studio Build Number

VisualStudio.17.Release/17.10.3+35013.160

### Device form factor

Desktop

### Additional context

I using the latest 8.1 preview from nuget.org: 8.1.240606-rc.

I tried to look into it, but I don't see the difference between the GridView in [8.1](https://github.com/CommunityToolkit/Windows/blob/0bab2c0359ab33b7ef9868496a2fe5175c5afe6b/components/ColorPicker/src/ColorPicker.xaml#L289) and [7.X](https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/6bfe8a5d21feb8818a8048b9fc41a84a70af8b0f/Microsoft.Toolkit.Uwp.UI.Controls.Input/ColorPicker/ColorPicker.xaml#L157)

### Help us help you

No, I'm unable to contribute a solution.

**Comment by niels9001** [comment]
This was by design, to be inline with other color palette areas like the one in W11 Settings:

![image](https://github.com/CommunityToolkit/Windows/assets/9866362/470bdbe8-6cc2-4827-beb5-ff6e01bfc1df)

**Comment by Marv51** [comment]
ok
