### ISSUE TITLE
[Icon Extensions][Windows] Can't assign FontFamily on FontIcon extension

### ISSUE THREAD

**Issue by morning4coffe-dev** [CommunityToolkit/Windows#487]
### Describe the bug

When I specify the FontFamily on any FontIcon extension, I get an error that it Failed to assign to property 'CommunityToolkit.WinUI.FontIconExtension.FontFamily'. This is needed for the icon to render correctly on e.g. Android.
[UnoCommunityToolkitExtBug.zip](https://github.com/user-attachments/files/16734158/UnoCommunityToolkitExtBug.zip)

### Steps to reproduce

Specify the FontFamily on any FontIcon extension, as following:

```xml
HeaderIcon="{toolkit:FontIcon Glyph=&#xE8C7;, FontFamily={ThemeResource SymbolThemeFontFamily}}"
```

### Expected behavior

Specifying the FontFamily should not throw an error on Windows as it does work well on other platforms.

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Visual Studio Version

2022

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by MartinZikmund** [comment]
I have hit this issue as well

**Comment by morning4coffe-dev** [comment]
@MartinZikmund You are right, this was the issue 🙃 the need for FontFamily on Uno targets should be resolved with https://github.com/unoplatform/uno/issues/17591
