### ISSUE TITLE
AdvancedCollectionView items are empty in gallery sample under Windows App SDK

### ISSUE THREAD

**Issue by Arlodotexe** [CommunityToolkit/Windows#513]
### Describe the bug

When running the gallery with the Wasdk head on the latest `main` commit, the 'AdvancedCollectionView' sample does not display items properly. The items are in the list, but the contents are empty. 

Wasdk:
![image](https://github.com/user-attachments/assets/068198ef-d9c3-4d3a-a8f8-9a42a7072b23)

UWP:
![image](https://github.com/user-attachments/assets/840f7e75-b676-41de-b2ae-b4f0e3819a6c)

### Steps to reproduce

```text
1. Clone the repo
2. Generate the gallery solution, include the Collections component and the wasdk multitarget/head.
3. Build and deploy the wasdk gallery 
4. Navigate to the 'AdvancedCollectionView' sample page and observe empty list items.
```

### Expected behavior

Contents should render the same as they did before Wasdk 1.6 and the same as on UWP. 

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by michael-hawker** [comment]
Ah, I was just about to try doing some testing/work on the sample here. @Arlodotexe what's the easiest way to turn off the AOT stuff, but still test the expected result on WASDK? I imagine just a prop somewhere?

Is it just turn `<PublishAot>true</PublishAot>` to false?

**Comment by michael-hawker** [comment]
Oh, I just noticed seeing `Exception thrown: 'System.NotSupportedException' in WinRT.Runtime.dll` in my output... then I ran again... and came back later and it seemed to be working?

![image](https://github.com/user-attachments/assets/e7c176a2-d3ad-45a5-94ca-c8f445debc8d)

Maybe it's a UI refresh issue in this scenario or something? Will have to see if I notice it again or not.

**Comment by michael-hawker** [comment]
Ah, just noticed the `PersonDataTemplate` is using regular `Binding` instead of `x:Bind`, that may be related, maybe?

**Comment by michael-hawker** [comment]
This looks like the same issue from #514 with issues in the sample around not using x:Bind in the data templates.

Have some fixes incoming which will resolve this, tested with Debug and Release.
