### ISSUE TITLE
Unable to Add CameraPreview to XAML WinUI3

### ISSUE THREAD

**Issue by corykroll** [CommunityToolkit/Windows#527]
### Describe the bug

I've downloaded NuGet package 
`CommunityToolkit.WinUI.Controls.CameraPreview 8.1.240916`

I then go into my XAML and try to add
`xmlns:winuicontrols="using:CommunityToolkit.WinUI.Controls"`
and it says undefined namespace

Reverting back to NuGet version 8.0.240109 fixes the issue.

### Steps to reproduce

```text
Download NuGet CommunityToolkit.WinUI.Controls.CameraPreview 8.1.240916
Try to add in XAML xmlns:winuicontrols="using:CommunityToolkit.WinUI.Controls"
```

### Expected behavior

The namespace would be accepted and I can add the CameraPreview widget into my XAML

### Code Platform

- [ ] UWP
- [X] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [X] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [X] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Visual Studio Version

2022

### Visual Studio Build Number

17.11.4

### Device form factor

Desktop

### Help us help you

No, I'm unable to contribute a solution.

**Comment by Arlodotexe** [comment]
@corykroll Have you updated your TFM and `WindowsSdkPackageVersion` to use v8.1 of the Community Toolkit? See [Important Changes](https://devblogs.microsoft.com/ifdef-windows/announcing-windows-community-toolkit-v8-1/#important-changes) in our release notes and [this issue thread](https://github.com/CommunityToolkit/Windows/issues/489#issuecomment-2328075085) for details.

**Comment by corykroll** [comment]
I've gotten it to work - thank you for the links!

I had to right-click the Project, select Properties, and click the
Application > General menu option and select 10.0.26100.0 from the Target
OS version dropdown.

Once that was done, I compiled the project and got another error:
A referenced assembly was compiled using a newer version of
Microsoft.Windows.SDK.NET.dll. Please update to a newer .NET SDK in order
to reference this assembly.

I closed Visual Studio, opened Visual Studio Installer, Modified by
existing install, selected the Individual Components tab at the tab,
searched for Windows SDK, and check the box for Windows 11 SDK
(10.0.26100.0)
I then clicked the Modify button and let Visual Studio installer add this
assembly.

Upon reopening my project and building it, it works.

I'm somewhat new to WinUI3 development, so I appreciate the nudge in the
right direction!
