### ISSUE TITLE
StaggeredLayout ItemsStretch Fill unstable when resizing

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Windows#571]
### Describe the bug

I notice this a lot more with WinUI 3, but also occurs with UWP. If you are resizing the window with the StaggeredLayout, it'll jump between where to put the items for filling the columns or not, it's probably on an edge case where it's not sure which one to do?

See the screenshot below for when it's in a bad state, but if you resize you can get to a point where the layout will flicker as you adjust the window. Recorded a video too.

FYI @Poker-sang, if you can help. I'll be pushing up an update soon with an updated CsWinRT version which should allow running this sample on main.

Otherwise just update WinAppSDK.props with the following for now locally:

```
    <PackageReference Condition="'$(HasWinUI)' == 'true'" Include="Microsoft.WindowsAppSDK" Version="1.6.241114003" />
    <PackageReference Condition="'$(HasWinUI)' == 'true'" Include="Microsoft.Windows.CsWinRt" Version="2.2.0" PrivateAssets="all"/>
```

### Steps to reproduce

```text
1. Open the primitives component
2. Run the sample app in UWP or WASDK (easier to see with WASDK)
3. Go to the StaggeredLayout sample
4. Set ItemsStretch to Fill
5. Resize window, see issue
```

### Expected behavior

No flicker/stable layout

### Screenshots

![Image](https://github.com/user-attachments/assets/8057ff71-3e9d-403c-947d-83c66c0affc6)

https://github.com/user-attachments/assets/1e6bdfe1-5cbc-4cdd-8e30-24342e2080ef

### Code Platform

- [x] UWP
- [x] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Device form factor

Desktop

### Additional context

Running from main

### Help us help you

Yes, but only if others can assist.

**Comment by michael-hawker** [comment]
FYI, If ItemsStretch is None, I don't see the same issue.

**Comment by Poker-sang** [comment]
Yes I found this issue before. But I saw that LinedFlowLayout also had this problem, which I thought was a common problem with Layout.

**Comment by Poker-sang** [comment]
Maybe it's a float point error, we just need `AvailableWidth` - 0.5 to leave a margin.

**Comment by AndrewKeepCoding** [comment]
I ran the sample and confirmed that the flickering is gone. 

https://github.com/user-attachments/assets/16b41d35-24e6-4374-97bc-3cae51ac7157
