### ISSUE TITLE
WinUI 3 Gallery Iconography Page is missing Icon Information!

### ISSUE THREAD

**Issue by DevTKSS** [CommunityToolkit/Windows#585]
### Describe the bug

tryed to lookup some Glyph codes, but the values are vanished from the icons, please fix this, gallery is a valualble resource for me

### Steps to reproduce

```text
open the Gallery on Windows and open the Iconography page click on e.g. Brightness like me and take a look on the propertys shown for the keys like CodeGlype or whatever, none is filled anymore!
```

### Expected behavior

the /someIdentifyer has been standing there before, which would be used to insert for usage in applications that icons

### Screenshots

![Image](https://github.com/user-attachments/assets/10397d8f-84d2-4226-bf74-3a8554f5f387)

### Code Platform

- [ ] UWP
- [x] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [ ] Windows 10 22H2 (Build 19045)
- [x] Windows 11 21H2 (Build 22000)
- [x] Other (specify)

### Other Windows Build number

general only opened the gallery on my windows 11 home device

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [x] Windows 11, version 22H2 (Build 22000)
- [x] Other (specify)

### Other SDK version

not relevant, looking up the values

### Visual Studio Version

2022

### Visual Studio Build Number

17.12.3

### Device form factor

Desktop

### Additional context

last few days the gallery application become very instable! Looking up things like always is resulting in exiting of the app after a not long time using it, thats not normal for it. please check it up, you are doing really great thing with it!
I can provide more video for the instability, but having no idea where that comes from. Having enough space on my device so should not be an issue.
Used Gallery Version (was not listed in your above questions) 2.5.0.0

### Help us help you

No, I'm unable to contribute a solution.

**Comment by AndrewKeepCoding** [comment]
This is not the [WinUI Gallery repo](https://github.com/microsoft/WinUI-Gallery/issues). By the way this is already fixed, and it's mentioned that the fix will be on the next version soon.
