### ISSUE TITLE
UWP .NET9 => v8.2.241221-build.1360 wrong dependencies (Uno.UI)

### ISSUE THREAD

**Issue by jp-weber** [CommunityToolkit/Windows#590]
### Describe the bug

With the latest nuget build v8.2.241221-build.1360 the dependencies seem to be pulled incorrectly, which means that Uno packages are included in a UWP project

### Steps to reproduce

```text
1. Create a new UWP project with dotnet 9
2. Install for example the package 'CommunityToolkit.Uwp.Controls.SettingsControls'
3. Build the app
```

### Expected behavior

No Uno packages.

### Screenshots

![Image](https://github.com/user-attachments/assets/8b7214c3-ff72-4227-b193-40b382a2d166)

![Image](https://github.com/user-attachments/assets/1c46e8ce-de3f-428c-824c-713c4b28213a)

### Code Platform

- [x] UWP
- [ ] WinAppSDK / WinUI 3
- [ ] Web Assembly (WASM)
- [ ] Android
- [ ] iOS
- [ ] MacOS
- [ ] Linux / GTK

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 10 21H2 (Build 19044)
- [x] Windows 10 22H2 (Build 19045)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [x] Windows 10, version 2004 (Build 19041)
- [ ] Windows 10, version 2104 (Build 20348)
- [ ] Windows 11, version 22H2 (Build 22000)
- [ ] Other (specify)

### Visual Studio Version

2022

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by Sergio0694** [comment]
Same as https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/238. When we merge #591 that should provide a workaround until we further split the packages. You should be able to try the new packages as soon as this is merged.
