### ISSUE TITLE
Port ColorPicker

### ISSUE THREAD

**Issue by niels9001** [CommunityToolkit/Windows#69]
```[tasklist]
### Base Porting Checklist
- [ ] Component name (to `CommunityToolkit.WinUI.Controls.ColorPicker`)
- [ ] Redesign, following the latest WinUI design guidelines
- [ ] Merge differences from UWP main to WinAppSDK / Uno forks
- [ ] Support for WASM via Uno Platform
- [ ] Improve Samples
- [ ] All brought over tests pass for UWP/WinAppSDK
```

```[tasklist]
### Known Issues
```

```[tasklist]
### Improvements
```

## Notable Changes
N/A

**Comment by niels9001** [comment]
We probably want to use a `Segmented` control here instead of the `Pivot`.

**Comment by Poker-sang** [comment]
Both `ColorPicker` and `ColorPickerButton` under namespace `CommunityToolkit.WinUI.UI.Controls` have a XAML binding failure problem. Would you them by the way when you port it?

**Comment by Arlodotexe** [comment]
Let's keep bug fixes in a separate PR from the initial port so we can track the change.

**Comment by Marv51** [comment]
Is this still blocked? I believe Segmented control was recently ported over. I am very much looking forward to using the ColorPicker.

**Comment by niels9001** [comment]
> Is this still blocked? I believe Segmented control was recently ported over. I am very much looking forward to using the ColorPicker.

Correct, no longer blocked - will remove the tag. Would you be interested in bringing this over from the old repo? Happy to jump in and help out with modernizing the UI!

**Comment by Jay-o-Way** [comment]
Is it `WinUI.Controls` or `Winui.UI.Controls`?

**Comment by niels9001** [comment]
> Is it `WinUI.Controls` or `Winui.UI.Controls`?

CommunityToolkit.WinUI.* is the new namespace used for 8.x. We are dropping the .UI. as we simplified the namespaces!

**Comment by 0x5bfa** [comment]
This issue prevents Files app from upgrading WCT package to 8...
Do you guys have a specific or rough date to work on this issue?
