### ISSUE TITLE
Bug report: WrapLayout

### ISSUE THREAD

**Issue by Poker-sang** [CommunityToolkit/Windows#70]
## Description
* When all the items in WrapLayout are Collapsed, the method WrapLayoutState.GetHeight() would throw "Nullable object must have a value."
* Once an item is collapsed in the WrapLayout(such as a Image that is loaded later), it would not be visible without refreshing.

## Possible solution
* Add a null discriminant statement to WrapLayoutState.GetHeight()
* Still measure and arrange collapsed items

**Comment by niels9001** [comment]
@Poker-sang Thanks for flagging this!

Is this something you'd like to PR a fix for 😊?

**Comment by Poker-sang** [comment]
Yes, I can fix this.

btw I implement another commonly used layout [JustifiedLayout](https://github.com/Poker-sang/JustifiedLayout). Do you think it could be added to the Toolkit?

**Comment by niels9001** [comment]
> Yes, I can fix this.
> 
> btw I implement another commonly used layout [JustifiedLayout](https://github.com/Poker-sang/JustifiedLayout). Do you think it could be added to the Toolkit?

Awesome.. great to hear!

`JustifiedLayout` sounds interesting.. feel free to open a Discussion (a.k.a. new Experiment) here so we can discuss it there! https://github.com/CommunityToolkit/Labs-Windows/discussions
