### ISSUE TITLE
Bug: Crash in AdvancedCollectionView if elements of different types with a common base class are added to the source

### ISSUE THREAD

**Issue by lhak** [CommunityToolkit/Windows#78]
Using a List\<BaseClass> as the source for an AdvancedCollectionView and adding elements of different types (derived from BaseClass) will lead to a crash in the Compare() function as it only uses the type of the first element to be compared.

I modified the code to use the type returned by GetGenericArguments() if the source is a generic type (e.g. List<>). I can submit a PR if wanted.

**Comment by niels9001** [comment]
@lhak Thanks for flagging this. Yes please! We checked in the port of the `AdvancedCollectionView` last week so feel free to put a PR in this repo 👍
