### ISSUE TITLE
Port TileControl

### ISSUE THREAD

**Issue by niels9001** [CommunityToolkit/Windows#88]
```[tasklist]
### Base Porting Checklist
- [ ] Component name (to `CommunityToolkit.WinUI.Controls.TileControl`)
- [ ] Redesign, following the latest WinUI design guidelines
- [ ] Merge differences from UWP main to WinAppSDK / Uno forks
- [ ] Support for WASM via Uno Platform
- [ ] Improve Samples
- [ ] All brought over tests pass for UWP/WinAppSDK
```

```[tasklist]
### Known Issues
```

```[tasklist]
### Improvements
```

## Notable Changes
N/A

**Comment by michael-hawker** [comment]
I believe this was closed as the `TileControl` was superseded by the `TilesBrush` in the media package. Probably something we should put in the [Migration Guide](https://github.com/CommunityToolkit/Windows/wiki/Migration-Guide-from-v7-to-v8).

There was this very old branch to enable animating tiled brushes here: https://github.com/CommunityToolkit/WindowsCommunityToolkit/compare/main...hawkerm:UWPCommunityToolkit:animatable-tile-brush, but required some base changes to the animation/pipeline APIs as well as potentially exposing some issues with the border effect in composition with certain edge-case settings (needed further investigation). Never got around to discussing the API changes with @Sergio0694.
