### ISSUE TITLE
Port TabbedCommandBar

### ISSUE THREAD

**Issue by niels9001** [CommunityToolkit/Windows#93]
```[tasklist]
### Base Porting Checklist
- [ ] Component name (to `CommunityToolkit.WinUI.Controls.TabbedCommandBar`)
- [ ] Redesign, following the latest WinUI design guidelines
- [ ] Merge differences from UWP main to WinAppSDK / Uno forks
- [ ] Support for WASM via Uno Platform
- [ ] Improve Samples
- [ ] All brought over tests pass for UWP/WinAppSDK
```

```[tasklist]
### Known Issues
```

```[tasklist]
### Improvements
```

## Notable Changes
N/A

**Comment by michael-hawker** [comment]
Talked to @yoshiask and they're going to take an initial look at it, thanks!

**Comment by niels9001** [comment]
> Talked to @yoshiask and they're going to take an initial look at it, thanks!
> 
> @niels9001 if we get the initial port in, maybe you can take a quick look at the template for styling?

Awesome! Yep, for sure - happy to help!

**Comment by mdtauk** [comment]
Having a quick look at Paint's VisualTree...
```Xml
<Ribbon>
    <ScrollContentPresenter>
        <Grid> // With columns for each toolbar/group
            <Border>
                <CollapsedToolbar>
                    <Grid>
                        <Border x:Name="ContentHolder"> // The Buttons that display in this toolbar
                            ... Custom Controls containing Buttons, SplitButtons, etc
                        </Border>
                        <Button x:Name=CollapsedButton> // The Button that displays when the toolbar isCollapsed
                    <TextBlock> // The Name of the toolbar/group
```
- The CollapsedButton is hidden when the CollapsedToolbar isCollapsed = False
- The Contents of the CollapsedToolbar render in a flyout when it is collapsed, whilst the CollapsedButton remains in the Ribbon

![image](https://github.com/CommunityToolkit/Windows/assets/7389110/52e25530-e0af-49b3-a6f6-87b54b951328)

![image](https://github.com/CommunityToolkit/Windows/assets/7389110/32fc00e7-12a7-4a51-9b7f-dd283fabdd6e)

![image](https://github.com/CommunityToolkit/Windows/assets/7389110/9a42ef10-ac8f-40a9-aca3-cefc605461dd)

I would guess there are Visual States that collapse as the width changes and goes below a threshold.

**Comment by mdtauk** [comment]
![image](https://github.com/CommunityToolkit/Windows/assets/7389110/d30fbd95-da78-46a1-826b-76b12a16a324)
Office and Outlook puts their toolbar controls within a floating panel

![image](https://github.com/CommunityToolkit/Windows/assets/7389110/a8c4cca9-5637-422d-b429-2319f1557568)
Something like this perhaps?
