### ISSUE TITLE
Port ImageEx

### ISSUE THREAD

**Issue by niels9001** [CommunityToolkit/Windows#95]
```[tasklist]
### Base Porting Checklist
- [ ] Component name (to `CommunityToolkit.WinUI.Controls.ImageEx`)
- [ ] Redesign, following the latest WinUI design guidelines
- [ ] Merge differences from UWP main to WinAppSDK / Uno forks
- [ ] Support for WASM via Uno Platform
- [ ] Improve Samples
- [ ] All brought over tests pass for UWP/WinAppSDK
```

```[tasklist]
### Known Issues
```

```[tasklist]
### Improvements
```

## Notable Changes
N/A

**Comment by niels9001** [comment]
Might be replaced by various extensions/behaviors

**Comment by ghost1372** [comment]
@michael-hawker can you take a look?

**Comment by michael-hawker** [comment]
@ghost1372 we haven't done anything with ItemsView yet, ImageEx isn't something we've tried to bring forward yet. It was never built/meant for virtualized/high-performance gallery scenarios, that's also one of the reasons we didn't bring it forward. https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/3250

I imagine it could be something that when `EnableLazyLoading` is enabled the control has no size? I could see that being a problem for ItemsRepeater/ItemsView?

**Comment by michael-hawker** [comment]
In the future, I probably see us not bringing `ImageEx` forward, but maybe some sort of brush/visual interop solution?

Would be cool to see something that takes some metadata (like image sized) to work with things like a placeholder image, shimmer, or https://blurha.sh/ to work in a consistent and coherent way that allow developers to have a lot of flexibility in dealing with loading images in a variety of different ways with the same API hook/interface?

@niels9001 @JustinXinLiu @Sergio0694 maybe something we could discuss and investigate using shimmer as base-case?

e.g.

```xml
<Border x:Name="ImageHolder">
   <Border.Background>
     <ui:LoadImageBrush ImageSource="<some remote slow resource>">
       <ui:LoadImageBrush.PlaceholderBrush>
         <ui:ShimmerBrush Duration="0:0:2"/>
       </ui:LoadImageBrush.PlaceholderBrush>
     </ui:LoadImageBrush>
   </Border.Background>
</Border>
```

I imagine we could hook into the PipelineBrush stuff maybe too?

**Comment by ghost1372** [comment]
> @ghost1372 we haven't done anything with ItemsView yet, ImageEx isn't something we've tried to bring forward yet. It was never built/meant for virtualized/high-performance gallery scenarios, that's also one of the reasons we didn't bring it forward. [CommunityToolkit/WindowsCommunityToolkit#3250](https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/3250)
> 
> I imagine it could be something that when `EnableLazyLoading` is enabled the control has no size? I could see that being a problem for ItemsRepeater/ItemsView?

Tnx for suggestion, i am using old version and i just posted my question here (i did not find better place), I Fixed issue with 2 way:
1. set a minimum width
2. using a placeholder image

**Comment by michael-hawker** [comment]
Thanks for the info @ghost1372, that makes it sound like ItemsRepeater was looking at the first item to get the width for every item and was getting `0` as LazyLoading doesn't place things initially. So then that would explain why they wouldn't get laid out until there was a layout update later, maybe?

I thought there was an issue about varying sized children in the platform repo about how ItemsRepeater uses the first child as a template, but I couldn't dig it up. Though, this is a slightly different case as the child to measure just isn't there yet.

All in all, with ItemsRepeater, this may just be an expected behavior that has to be worked around in this scenario with either of the methods you mentioned.
